apiVersion: v1
kind: Service
metadata:
  name: shopkeeper-api
  labels:
    app.kubernetes.io/name: shopkeeper-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: shopkeeper-api
  ports:
    - name: http
      port: 8000
      targetPort: http
